databases:
  - name: Renderで作成したDBアプリ名
    databaseName: adusu_db
    user: Renderで作成したRailsのアプリ名
    region: singapore

services:
  - type: web
    name: adusu_rails_demo
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: adusu_demo_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false